name: Deploy EC2 Instance

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch (you can change this to your desired branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.SECRET_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Launch EC2 instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0f58b397bc5c1f2e8 \  # Replace with your preferred AMI ID
            --count 1 \
            --instance-type t2.micro \  # Replace with your preferred instance type
            --key-name DEVESHKEY \  # Replace with your key pair name
            --security-group-ids sg-02226b9f786b1d1dc \  # Replace with your security group ID
            --subnet-id subnet-094d8dd61df99b340  # Replace with your subnet ID
