name: Create EC2 Instance

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch. Adjust as necessary.

jobs:
  create-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change to your preferred region

      - name: Run EC2 instance script
        run: |
          #!/bin/bash
          # Define instance parameters
          INSTANCE_TYPE="t2.micro"
          AMI_ID="ami-0f58b397bc5c1f2e8"  # Replace with your preferred AMI ID
          KEY_NAME="DEVESHKEY"  # Replace with your key pair name
          
          # Create EC2 instance
          aws ec2 run-instances \
            --image-id $AMI_ID \
            --count 1 \
            --instance-type $INSTANCE_TYPE \
            --key-name $KEY_NAME \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHubActionInstance}]'
